name: "Build"
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - run: ls -lart ${{ github.workspace }}
        - run: ./scripts/setup.sh
        - run: gradle test
