name: "CI & CD"
on:
  push:
    tags:
      - '*'
jobs:
  Build-Release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19
      - name: Start Databases
        run: ./scripts/setup.sh
      - name: Release
        uses: gradle/gradle-build-action@v2
        env:
          PACKAGE_STORE_USERNAME: ${{ secrets.PACKAGE_STORE_USERNAME }}
          PACKAGE_STORE_TOKEN: ${{ secrets.PACKAGE_STORE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_RELEASE_BUILD: true
        with:
          gradle-version: 8.2.1
          arguments: clean test build publish --info --stacktrace
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: Test Artifacts
          path: exposed-tests/build/test-results/*/*.xml
