name: 'Test Reports'
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Postgres Test Results
        uses: dorny/test-reporter@v1.5.0
        with:
          artifact: Test Artifacts
          name: Postgres Test Results
          path: exposed-tests/build/test-results/postgresTest/*.xml
          reporter: java-junit
      - name: Upload Postgres Test Results
        uses: dorny/test-reporter@v1.5.0
        with:
          artifact: Test Artifacts
          name: Postgres Test Results
          path: exposed-tests/build/test-results/postgresTest/*.xml
          reporter: java-junit
      - name: Upload Postgres Test Results
        uses: dorny/test-reporter@v1.5.0
        with:
          artifact: Test Artifacts
          name: Postgres Test Results
          path: exposed-tests/build/test-results/mysql51Test/*.xml
          reporter: java-junit
